# Generated by Django 5.2.9 on 2025-12-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Semester', 'Semester')], default='Internal', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
    ]
